<?php
/**
 * Copyright Serhii Borodai (c) 2017-2018.
 */

/**
 * Created by Serhii Borodai <clarifying@gmail.com>
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Sample RoomX application</h1>
    <hr>
    <div class="row">
        <span class="text-primary">Correct&nbsp;</span>is full CRUD with new price storage
    </div>
    <div class="row">
        <span class="text-primary">Original&nbsp;</span> is demo just CR operations based on original technical task database structure
    </div>
</div>
